# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MaWi(object):
    def setupUi(self, MaWi):
        MaWi.setObjectName("MaWi")
        MaWi.resize(526, 357)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MaWi.sizePolicy().hasHeightForWidth())
        MaWi.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MaWi)
        self.centralwidget.setObjectName("centralwidget")
        self.gain_slider = QtWidgets.QSlider(self.centralwidget)
        self.gain_slider.setEnabled(False)
        self.gain_slider.setGeometry(QtCore.QRect(50, 280, 281, 21))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gain_slider.sizePolicy().hasHeightForWidth())
        self.gain_slider.setSizePolicy(sizePolicy)
        self.gain_slider.setMinimum(1)
        self.gain_slider.setMaximum(3500)
        self.gain_slider.setPageStep(1)
        self.gain_slider.setOrientation(QtCore.Qt.Horizontal)
        self.gain_slider.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.gain_slider.setTickInterval(100)
        self.gain_slider.setObjectName("gain_slider")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(50, 260, 47, 13))
        self.label.setObjectName("label")
        self.gain_input = QtWidgets.QLineEdit(self.centralwidget)
        self.gain_input.setEnabled(False)
        self.gain_input.setGeometry(QtCore.QRect(81, 257, 113, 20))
        self.gain_input.setInputMask("")
        self.gain_input.setMaxLength(4)
        self.gain_input.setObjectName("gain_input")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 310, 47, 13))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 300, 47, 13))
        self.label_3.setObjectName("label_3")
        self.connect_button = QtWidgets.QPushButton(self.centralwidget)
        self.connect_button.setGeometry(QtCore.QRect(60, 40, 93, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.connect_button.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.connect_button.setFont(font)
        self.connect_button.setObjectName("connect_button")
        self.info_label = QtWidgets.QLabel(self.centralwidget)
        self.info_label.setGeometry(QtCore.QRect(60, 80, 261, 141))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info_label.sizePolicy().hasHeightForWidth())
        self.info_label.setSizePolicy(sizePolicy)
        self.info_label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.info_label.setObjectName("info_label")
        self.snap_button = QtWidgets.QPushButton(self.centralwidget)
        self.snap_button.setEnabled(False)
        self.snap_button.setGeometry(QtCore.QRect(230, 40, 93, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.snap_button.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.snap_button.setFont(font)
        self.snap_button.setObjectName("snap_button")
        self.live_button = QtWidgets.QPushButton(self.centralwidget)
        self.live_button.setEnabled(False)
        self.live_button.setGeometry(QtCore.QRect(360, 40, 93, 28))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.live_button.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.live_button.setFont(font)
        self.live_button.setObjectName("live_button")
        MaWi.setCentralWidget(self.centralwidget)

        self.retranslateUi(MaWi)
        QtCore.QMetaObject.connectSlotsByName(MaWi)

    def retranslateUi(self, MaWi):
        _translate = QtCore.QCoreApplication.translate
        MaWi.setWindowTitle(_translate("MaWi", "Camera control"))
        self.label.setText(_translate("MaWi", "Gain"))
        self.gain_input.setText(_translate("MaWi", "1"))
        self.label_2.setText(_translate("MaWi", "1"))
        self.label_3.setText(_translate("MaWi", "3500"))
        self.connect_button.setText(_translate("MaWi", "Connect"))
        self.info_label.setText(_translate("MaWi", "Camera info:"))
        self.snap_button.setText(_translate("MaWi", "Do Snap"))
        self.live_button.setText(_translate("MaWi", "Live"))

